name: Deploy petedorc.com

on:
  push:
    branches: [ main ]
    paths: [ "site/**" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: us-east-1
      S3_BUCKET: petedorc-site
      CF_DIST_ID: E3VLE90V78FWL
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::637423348409:role/GitHubDeployPetedorc
          aws-region: ${{ env.AWS_REGION }}

            - name: Who am I?
        run: aws sts get-caller-identity

      - name: Show env + list CloudFront dists
        run: |
          echo "CF_DIST_ID=[$CF_DIST_ID]"   # brackets make whitespace visible
          aws cloudfront list-distributions --query "DistributionList.Items[].{Id:Id,Domain:DomainName,Aliases:Aliases.Items}" --output table

      - name: Invalidate CloudFront (trimmed ID)
        run: |
          ID="$(echo "$CF_DIST_ID" | tr -d '[:space:]')"   # strip hidden whitespace/newlines
          aws cloudfront get-distribution --id "$ID"
          aws cloudfront create-invalidation --distribution-id "$ID" --paths "/*"
