name: Deploy petedorc.com
on:
  push:
    branches: [ main ]
    paths: [ "site/**" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read }
    env:
      AWS_REGION: us-east-1
      S3_BUCKET: petedorc-site
      CF_DIST_ID: E2V3LE90V78FWL
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::637423348409:role/GitHubDeployPetedorc
          aws-region: ${{ env.AWS_REGION }}
      - name: Sync to S3
        run: aws s3 sync site "s3://$S3_BUCKET" --delete
      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id "$CF_DIST_ID" --paths "/*"
