name: Deploy petedorc.com

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ "site/**" ]   # only run when /site changes

env:
  AWS_REGION: us-east-1
  S3_BUCKET: petedorc-site
  CF_DIST_ID: E2V3LE90V78FWL
  SOURCE_PATH: "site"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::637423348409:role/GitHubDeployPetedorc
          aws-region: ${{ env.AWS_REGION }}

      # Short-cache HTML so updates show up quickly
      - name: Sync HTML
        run: |
          aws s3 sync "$SOURCE_PATH" "s3://$S3_BUCKET" \
            --exclude "*" --include "*.html" \
            --cache-control "max-age=60,public" \
            --delete

      # Long-cache everything else (images, css, js, etc.)
      - name: Sync assets
        run: |
          aws s3 sync "$SOURCE_PATH" "s3://$S3_BUCKET" \
            --exclude ".git/*" --exclude ".github/*" --exclude "*.html" \
            --cache-control "max-age=31536000,public,immutable" \
            --delete

      # Invalidate only what can change or is HTML-driven
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "$CF_DIST_ID" \
            --paths "/index.html" "/case-studies/*" "/assets/*"
