name: Deploy petedorc.com

on:
  push:
    branches: [ main ]
    paths:
      - "site/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: us-east-1
      S3_BUCKET: petedorc-site
      CF_DIST_ID: E3VLE90V78FWL

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::637423348409:role/GitHubDeployPetedorc
          aws-region: ${{ env.AWS_REGION }}

      - name: Who am I?
        run: aws sts get-caller-identity

      - name: Show env + list CloudFront dists
        run: |
          echo "CF_DIST_ID=[$CF_DIST_ID]"
          aws cloudfront list-distributions --query "DistributionList.Items[].{Id:Id,Domain:DomainName,Aliases:Aliases.Items}" --output table

      - name: Sync to S3 (root)
        run: aws s3 sync site "s3://$S3_BUCKET" --delete

      - name: Invalidate CloudFront (trimmed ID)
        run: |
          ID="$(echo "$CF_DIST_ID" | tr -d '[:space:]')"
          aws cloudfront get-distribution --id "$ID"
          aws cloudfront create-invalidation --distribution-id "$ID" --paths "/*"
